# Generated by Django 5.0.3 on 2024-03-12 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_transfer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transfer',
            new_name='Transfer_money',
        ),
    ]
